### ISSUE TITLE
Fix typo error in function name

### ISSUE THREAD

**Issue by ansidev** [dalenguyen/firebase-functions-helper#1]
https://github.com/dalenguyen/firebase-functions-helper/blob/e710a38111a2302a3d7b4df835cbdd9f20b834cb/src/firestore.ts#L26
Current name: `creatNewDocument` (missing letter `e`)
Right name: `createNewDocument`

**Comment by dalenguyen** [comment]
Thanks @ansidev, I fixed the typo :)
