### ISSUE TITLE
Create multiple users in Aaray

### ISSUE THREAD

**Issue by jephjohnson** [dalenguyen/firebase-functions-helper#10]
I saw the documentation of being able to create a 
Single user but I would like to pass an array of data
To create multiple users. Is this possible?

*I am using firebase real-time database and storage

**Comment by dalenguyen** [comment]
Hi @jephjohnson, it's totally possible. You can loop through your array, and run the the createUser(). You may want to delay the loop though. 

I think that Firebase has import user feature that you may want to use.

**Comment by dalenguyen** [comment]
Close due to inactivity.
