### ISSUE TITLE
queryData() return only ONE RECORD

### ISSUE THREAD

**Issue by Tan-nn** [dalenguyen/firebase-functions-helper#12]
Hi @dalenguyen 
I used `queryData` as your guide and its response only one record while FireStore has 2 records.

Can you  help to check, Thank you!

```javascript
app.get('/ielts-reading-level/:levelSlug', (req, res) => {
   const {levelSlug} = req.params
    const queryArray = [['levelSlug', '==',  levelSlug]];
    firebaseHelper.firestore
        .queryData(db, levelsCollection, queryArray)
        .then(data => res.status(200).send(data))
        .catch(error => {
            console.error('ERROR::: ', error)
            res.status(500).send(error.message)
        })
})
```

Response:
```
{
    "PfX9074Z1uvaMT18djas": {
        "name": "Children",
        "description": "For children",
        "levelSlug": "level1",
        "slug": "level1"
    }
}
````

**Comment by dalenguyen** [comment]
Hi @Tan-nn, 

I just check query test cases, it does return multiple results. Can you replace this to test if it still returns one record on the log?
  
```
res.status(200).send(data) -> console.log(data)
```
Try to query another parameter to test if it's still the same, and can you post a sample of your data? You can use the backup function to do it. 

```
firebaseHelper.firestore.backup(db, collectionName)
```

**Comment by Tan-nn** [comment]
@dalenguyen thanks for your reply, I have changed to use `firebase-admin`,  It cool as your module
