### ISSUE TITLE
Update document

### ISSUE THREAD

**Issue by ansidev** [dalenguyen/firebase-functions-helper#13]
Hi @dalenguyen,

I have seen the breaking change in function queryData between 0.6.3 and 0.6.4. You should notice about it in `README.md` on git repository homepage.

Thank you!

**Comment by dalenguyen** [comment]
Hi @ansidev, it's updated in the firestore documents.

https://github.com/dalenguyen/firebase-functions-helper/blob/master/docs/firestore.md

But you're right. I forgot to update the changelogs file, I will do it this weekend. Thanks,
