### ISSUE TITLE
I need create subcollection with document

### ISSUE THREAD

**Issue by MaxiTalenti** [dalenguyen/firebase-functions-helper#15]
Hi, i need create a subcollection with a exist document or not, how i can do?

**Comment by dalenguyen** [comment]
You can check if the document exists or not, then decide what you want to with it. I need more detail if you want more information.

https://github.com/dalenguyen/firebase-functions-helper/blob/master/docs/firestore.md#8-check-whether-a-document-exists

**Comment by dalenguyen** [comment]
Closed due to inactivity.
