### ISSUE TITLE
can admin sdk be accessed using firebase-functions-helper

### ISSUE THREAD

**Issue by d17129503** [dalenguyen/firebase-functions-helper#20]
I am trying to make firebaseHelper.firebase.auth().verifyIdToken()

looking for alternative way to achieve this

Basically in my app
1. validating the idToken 
2. if user is valid then he can perform crud operations

**Comment by dalenguyen** [comment]
Hi @d17129503 , please updated to v0.7.3. It now supports auth() function.

**Comment by bharath-exads** [comment]
Thanks :)
