### ISSUE TITLE
Can't find declaration file

### ISSUE THREAD

**Issue by brandtdaniels** [dalenguyen/firebase-functions-helper#23]
Receiving this error

src/index.ts:4:33 - error TS7016: Could not find a declaration file for module 'firebase-functions-helper'. '/Users/asdf/Developer/git/Personal/my-api/functions/node_modules/firebase-functions-helper/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/firebase-functions-helper` if it exists or add a new declaration (.d.ts) file containing `declare module 'firebase-functions-helper';`

**Comment by JoshuaFry** [comment]
Doing this
`const firebaseHelper = require('firebase-functions-helper');`
instead of this
`import * as firebaseHelper from "firebase-functions-helper";`

fixed this import issue for me, not sure why...

**Comment by dalenguyen** [comment]
@brandtdaniels @JoshuaFry I just updated the package to v0.7.5. Please try it again. Thanks,
