### ISSUE TITLE
How to write our own implementations 

### ISSUE THREAD

**Issue by ffalpha** [dalenguyen/firebase-functions-helper#28]
Hello.Thanks for this amazing package. This sound like stupid question.But I really like to add my own implementations to this package.How to do it ? For example instead of updating a document is it possible to write code segment to append items into a firestore document? I tired to do it by reading firestore documentation. But didn't work. My question If can add something that to which file should I add those custom code parts ?Thank you

**Comment by dalenguyen** [comment]
Hi @ffalpha, you can help to contribute to this project by fork & update the code for this package. You can see an example on how to contribute in this article. 

https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by ffalpha** [comment]
@dalenguyen Thank you for you comment. Actually I know how to contribute.I think you have misunderstood my problem. Here is what I am trying do.I want to make a functions which can append data to array  in a firestore document .As per the google documentation there is a way to to do this .I tried to do it by reading the documentation.But it didn't work. My real question If I want to make my own function adding it to the firebase-functions-helper/src/firestore.ts would be enough ? I am still a beginner .If you could point me to the right direction that will be great. If everything went I will surely contribute. Thank you
