### ISSUE TITLE
FirebaseHelper backup undefined error

### ISSUE THREAD

**Issue by osaetinevbuoma** [dalenguyen/firebase-functions-helper#34]
While using v0.11.0, I noticed that calls to `firebaseHelper.firestore.backup()` resulted in a `cannot read property 'backup; of undefined` error. I had to switch to v0.7.5. The implementation of the backup function in the two versions is different.

**Comment by dalenguyen** [comment]
Hi @osaetinevbuoma, the implementation has changed to make it lighter when importing the functions. 

```
import { firestoreHelper } from 'fibase-function-helper'

// use this function for backing up
firestoreHelper.backup('collection-name')
```

**Comment by osaetin-tails** [comment]
I see. Great! Thanks.
