### ISSUE TITLE
Could not find a declaration file for module 'firebase-functions-helper'

### ISSUE THREAD

**Issue by Robin--** [dalenguyen/firebase-functions-helper#9]
Good morning,
Im getting: 

[ts]
Could not find a declaration file for module 'firebase-functions-helper'. 'c:/Projects/firebase-typescript-express-functions/node_modules/firebase-functions-helper/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/firebase-functions-helper` if it exists or add a new declaration (.d.ts) file containing `declare module 'firebase-functions-helper';` [7016]

When I attempt to npm install firebase-functions-helper

Any ideas?

**Comment by dalenguyen** [comment]
Hi @Robin--, you can bypass it by adding this line to your tsconfig.json 

   `"noImplicitAny": false`

I'll try to fix this over the weekend. It would be great if you can provide a sample of the issue that you are having.
